[package]
name = "vouc"
version = "0.1.0"
authors = ["Dmitrii Goriunov <goriunovd@gmail.com>"]
edition = "2015"

[dependencies]
r2d2 = "0.8"
hyper = "0.12"
tokio = "0.1"
diesel = { version = "1", features = ["postgres", "r2d2"] }
futures = "0.1"
tokio-threadpool = "0.1"